[package]
name = "rr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.42.0"
crossterm = { version = "0.26.0", features = ["event-stream"] }
fasthash = "0.4.0"
futures = "0.3.26"
futures-timer = "3.0.2"
notify-rust = "4.7.0"
pad = "0.1.6"
parking_lot = "0.12.1"
patricia_tree = "0.5.5"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
unix_mode = "0.1.3"
whoami = "1.3.0"
