[package]
name = "rfm"
version = "0.1.0"
edition = "2021"
authors = ["Christian Hammermeister"]
description = "A super fast file-manager written in rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
cached = "0.42.0"
clap = {version = "4.1.6", features = ["derive"]}
crossterm = { version = "0.26.0", features = ["event-stream"] }
fasthash = "0.4.0"
fs_extra = "1.3.0"
futures = "0.3.26"
futures-timer = "3.0.2"
image = "0.24.5"
notify = {version = "5.1.0", default-features = false, features = ["macos_fsevent"]}
notify-rust = "4.7.1"
pad = "0.1.6"
parking_lot = "0.12.1"
patricia_tree = "0.5.5"
rand = "0.8.5"
tempfile = "3.3.0"
thiserror = "1.0.38"
time = {version = "0.3.19", features = ["formatting"]}
tokio = { version = "1.25.0", features = ["full"] }
unix_mode = "0.1.3"
users = "0.11.0"
whoami = "1.3.0"
