[general]
search        = [ "/", "search", "f" ]
mark          = [ " " ]
next          = [ "n" ]
previous      = [ "N" ]
view_trash    = [ "gT" ]
toggle_hidden = [ "zh" ]
toggle_log    = [ "devlog" ]
quit          = [ "q", "Q", "exit" ]

[movement]
up                 = [ "k" ]
down               = [ "j" ]
left               = [ "h" ]
right              = [ "l" ]
top                = [ "gg" ]
bottom             = [ "G" ]
page_forward       = [ "ctrl-f" ]
page_backward      = [ "ctrl-b" ]
half_page_forward  = [ "ctrl-d" ]
half_page_backward = [ "ctrl-u" ]
jump_previous      = [ "''" ]
jump_to = [ ["gh", "~"],
            ["gc", "~/.config"],
            ["gs", "~/.scripts"],
            ["gb", "~/Bilder"],
            ["gd", "~/Dokumente"],
            ["gD", "~/Downloads"],
            ["gm", "~/Musik"],
            ["gr", "/"],
            ["ge", "/etc"],
            ["gu", "/usr"]]

[manipulation]
change_directory = [ "cd" ]
rename           = [ "rename" ]
mkdir            = [ "mkdir" ]
touch            = [ "touch" ]
cut              = [ "cut", "dd", "ctrl-x" ]
copy             = [ "copy", "yy", "ctrl-c" ]
delete           = [ "delete" ]
paste            = [ "paste", "pp", "ctrl+v" ]
paste_overwrite  = [ "po", "ctrl+V" ]
